CREATE TABLE all_raw (
    "index"                                                               INTEGER,
    "StudyName"                                                           TEXT,
    "Name"                                                                TEXT,
    "Age"                                                                 INTEGER,
    "Gender"                                                              TEXT,
    "StimulusName"                                                        TEXT,
    "SlideType"                                                           TEXT,
    "EventSource"                                                         TEXT,
    "Timestamp"                                                           TEXT,
    "PostMarker"                                                          TEXT,
    "Timestamp RAW (no units) (Shimmer Sensor)"                           REAL,
    "Timestamp CAL (mSecs) (Shimmer Sensor)"                              REAL,
    "VSenseBatt RAW (no units) (Shimmer Sensor)"                          REAL,
    "VSenseBatt CAL (mVolts) (Shimmer Sensor)"                            REAL,
    "GSR RAW (no units) (Shimmer Sensor)"                                 REAL,
    "GSR CAL (kOhms) (Shimmer Sensor)"                                    REAL,
    "GSR CAL (µSiemens) (Shimmer Sensor)"                                 REAL,
    "Packet reception rate RAW (no units) (Shimmer Sensor)"               REAL,
    "GSR Quality (Shimmer Sensor)"                                        TEXT,
--     "Timestamp RAW (no units) (Shimmer)",
--     "Timestamp CAL (mSecs) (Shimmer)",
--     "VSenseBatt RAW (no units) (Shimmer)",
--     "VSenseBatt CAL (mVolts) (Shimmer)",
--     "GSR RAW (no units) (Shimmer)",
--     "GSR CAL (kOhms) (Shimmer)",
--     "GSR CAL (µSiemens) (Shimmer)",
--     "Packet reception rate RAW (no units) (Shimmer)",
--     "GSR Quality (Shimmer)",
    "Delta (1-3 Hz) Asymmetry Log 10 F4/F3 (ABM EEG Frontal Asymmetry)"   REAL,
    "Delta (1-3 Hz) F3 Average (ABM EEG Frontal Asymmetry)"               REAL,
    "Delta (1-3 Hz) F4 Average (ABM EEG Frontal Asymmetry)"               REAL,
    "Theta (4-7 Hz) Asymmetry Log 10 F4/F3 (ABM EEG Frontal Asymmetry)"   REAL,
    "Theta (4-7 Hz) F3 Average (ABM EEG Frontal Asymmetry)"               REAL,
    "Theta (4-7 Hz) F4 Average (ABM EEG Frontal Asymmetry)"               REAL,
    "Alpha (8-12 Hz) Asymmetry Log 10 F4/F3 (ABM EEG Frontal Asymmetry)"  REAL,
    "Alpha (8-12 Hz) F3 Average (ABM EEG Frontal Asymmetry)"              REAL,
    "Alpha (8-12 Hz) F4 Average (ABM EEG Frontal Asymmetry)"              REAL,
    "Beta (13-25 Hz) Asymmetry Log 10 F4/F3 (ABM EEG Frontal Asymmetry)"  REAL,
    "Beta (13-25 Hz) F3 Average (ABM EEG Frontal Asymmetry)"              REAL,
    "Beta (13-25 Hz) F4 Average (ABM EEG Frontal Asymmetry)"              REAL,
    "Gamma (26-40 Hz) Asymmetry Log 10 F4/F3 (ABM EEG Frontal Asymmetry)" REAL,
    "Gamma (26-40 Hz) F3 Average (ABM EEG Frontal Asymmetry)"             REAL,
    "Gamma (26-40 Hz) F4 Average (ABM EEG Frontal Asymmetry)"             REAL
);

CREATE TABLE clean (
    "index"                                                               INTEGER,
    "StudyName"                                                           TEXT,
    "Name"                                                                TEXT,
    "Age"                                                                 INTEGER,
    "Gender"                                                              TEXT,
    "StimulusName"                                                        TEXT,
    "SlideType"                                                           TEXT,
    "EventSource"                                                         TEXT,
    "Timestamp"                                                           TEXT,
    "PostMarker"                                                          TEXT,
--     "Timestamp RAW (no units) (Shimmer Sensor)"                           REAL,
--     "Timestamp CAL (mSecs) (Shimmer Sensor)"                              REAL,
--     "VSenseBatt RAW (no units) (Shimmer Sensor)"                          REAL,
--     "VSenseBatt CAL (mVolts) (Shimmer Sensor)"                            REAL,
--     "GSR RAW (no units) (Shimmer Sensor)"                                 REAL,
--     "GSR CAL (kOhms) (Shimmer Sensor)"                                    REAL,
--     "GSR CAL (µSiemens) (Shimmer Sensor)"                                 REAL,
--     "Packet reception rate RAW (no units) (Shimmer Sensor)"               REAL,
--     "GSR Quality (Shimmer Sensor)"                                        TEXT,
    "Timestamp RAW (no units) (Shimmer)",
    "Timestamp CAL (mSecs) (Shimmer)",
    "VSenseBatt RAW (no units) (Shimmer)",
    "VSenseBatt CAL (mVolts) (Shimmer)",
    "GSR RAW (no units) (Shimmer)",
    "GSR CAL (kOhms) (Shimmer)",
    "GSR CAL (µSiemens) (Shimmer)",
    "Packet reception rate RAW (no units) (Shimmer)",
    "GSR Quality (Shimmer)",
    "Delta (1-3 Hz) Asymmetry Log 10 F4/F3 (ABM EEG Frontal Asymmetry)"   REAL,
    "Delta (1-3 Hz) F3 Average (ABM EEG Frontal Asymmetry)"               REAL,
    "Delta (1-3 Hz) F4 Average (ABM EEG Frontal Asymmetry)"               REAL,
    "Theta (4-7 Hz) Asymmetry Log 10 F4/F3 (ABM EEG Frontal Asymmetry)"   REAL,
    "Theta (4-7 Hz) F3 Average (ABM EEG Frontal Asymmetry)"               REAL,
    "Theta (4-7 Hz) F4 Average (ABM EEG Frontal Asymmetry)"               REAL,
    "Alpha (8-12 Hz) Asymmetry Log 10 F4/F3 (ABM EEG Frontal Asymmetry)"  REAL,
    "Alpha (8-12 Hz) F3 Average (ABM EEG Frontal Asymmetry)"              REAL,
    "Alpha (8-12 Hz) F4 Average (ABM EEG Frontal Asymmetry)"              REAL,
    "Beta (13-25 Hz) Asymmetry Log 10 F4/F3 (ABM EEG Frontal Asymmetry)"  REAL,
    "Beta (13-25 Hz) F3 Average (ABM EEG Frontal Asymmetry)"              REAL,
    "Beta (13-25 Hz) F4 Average (ABM EEG Frontal Asymmetry)"              REAL,
    "Gamma (26-40 Hz) Asymmetry Log 10 F4/F3 (ABM EEG Frontal Asymmetry)" REAL,
    "Gamma (26-40 Hz) F3 Average (ABM EEG Frontal Asymmetry)"             REAL,
    "Gamma (26-40 Hz) F4 Average (ABM EEG Frontal Asymmetry)"             REAL
);